# Generated by Django 4.0.2 on 2022-03-03 19:59

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
